const data = {
  products: [
    {
      id: "1",
      brand: "Brand A",
      description: "Description A",
      price: 200,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 0,
      gender: "male",
    },
    {
      id: "2",
      brand: "Brand B",
      description: "Description B",
      price: 150,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 20,
      gender: "male",
    },
    {
      id: "3",
      brand: "Brand C",
      description: "Description C",
      price: 175,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 30,
      gender: "male",
    },
    {
      id: "4",
      brand: "Brand D",
      description: "Description D",
      price: 125,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 40,
      gender: "male",
    },
    {
      id: "5",
      brand: "Brand E",
      description: "Description E",
      price: 100,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 50,
      gender: "male",
    },
    {
      id: "6",
      brand: "Brand F",
      description: "Description F",
      price: 190,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 0,
      gender: "male",
    },
    {
      id: "7",
      brand: "Brand G",
      description: "Description G",
      price: 140,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 10,
      gender: "male",
    },
    {
      id: "8",
      brand: "Brand H",
      description: "Description H",
      price: 165,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 20,
      gender: "male",
    },
    {
      id: "9",
      brand: "Brand I",
      description: "Description I",
      price: 115,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 30,
      gender: "male",
    },
    {
      id: "10",
      brand: "Brand J",
      description: "Description J",
      price: 90,
      image: "/itemphotos/irene-kredenets-dwKiHoqqxk8-unsplash.jpg",
      stock: 40,
      gender: "male",
    },
    {
      id: "11",
      brand: "Brand A",
      description: "Description A",
      price: 200,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 0,
      gender: "female",
    },
    {
      id: "12",
      brand: "Brand B",
      description: "Description B",
      price: 150,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 20,
      gender: "female",
    },
    {
      id: "13",
      brand: "Brand C",
      description: "Description C",
      price: 175,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 30,
      gender: "female",
    },
    {
      id: "14",
      brand: "Brand D",
      description: "Description D",
      price: 125,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 40,
      gender: "female",
    },
    {
      id: "15",
      brand: "Brand E",
      description: "Description E",
      price: 100,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 50,
      gender: "female",
    },
    {
      id: "16",
      brand: "Brand F",
      description: "Description F",
      price: 190,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 0,
      gender: "female",
    },
    {
      id: "17",
      brand: "Brand G",
      description: "Description G",
      price: 140,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 10,
      gender: "female",
    },
    {
      id: "18",
      brand: "Brand H",
      description: "Description H",
      price: 165,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 20,
      gender: "female",
    },
    {
      id: "19",
      brand: "Brand I",
      description: "Description I",
      price: 115,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 30,
      gender: "female",
    },
    {
      id: "20",
      brand: "Brand J",
      description: "Description J",
      price: 90,
      image: "/itemphotos/ryan-plomp-jvoZ-Aux9aw-unsplash.jpg",
      stock: 40,
      gender: "female",
    },
  ],
};

export default data;
